name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      # ===================== REPO =====================
      - name: Checkout repo
        uses: actions/checkout@v4

      # ===================== JAVA 25 =====================
      - name: Install JDK 25
        run: |
          sudo apt update
          sudo apt install -y wget gnupg curl

          wget -O jdk25.deb https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.deb
          sudo apt install -y ./jdk25.deb
          rm jdk25.deb

      # ===================== NGROK =====================
      - name: Install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null

          echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null

          sudo apt update
          sudo apt install -y ngrok

      # ===================== AUTH =====================
      - name: Configure ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      # ===================== EULA =====================
      - name: Accept EULA
        run: echo "eula=true" > eula.txt

      # ===================== NGROK START + WAIT =====================
      - name: Start ngrok tunnel and get URL
        run: |
          nohup ngrok tcp 25565 > ngrok.log 2>&1 &

          echo "Waiting for ngrok to generate public URL..."

          while true; do
            URL=$(curl -s http://127.0.0.1:4040/api/tunnels \
              | grep -o '"public_url":"[^"]*' \
              | head -n 1 \
              | cut -d'"' -f4 || true)

            if [ ! -z "$URL" ]; then
              echo "================ NGROK LINK ================"
              echo "$URL"
              echo "==========================================="
              break
            fi

            sleep 2
          done

      # ===================== SERVER =====================
      - name: Run PaperMC Server
        run: |
          export JAVA_HOME=/usr/lib/jvm/jdk-25.0.3-oracle-x64
          export PATH=$JAVA_HOME/bin:$PATH

          java -version

          java -Xms2G -Xmx4G -jar paper.jar --nogui
